title:               portfolio - weronika zak
url:                 https://weronikazak.github.io
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /project/:num

contacturl:           /pages/contact/
abouturl:             /pages/about/

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Weronika Żak
  url:               weronikazak.github.io
  email:             weronika.w.zak@gmail.com

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist

defaults:
- scope:
    path: "images"
  values:
    image: true