title:               portfolio - weronika zak
url:                 https://weronikazak.github.io
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           /:year/:title/
paginate:            5
paginate_path:       /project/:num

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Weronika Zak
  url:               weronikazak.github.io
  email:             weronika.w.zak@gmail.com

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist

defaults:
- scope:
    path: "assets/img"
  values:
    image: true